geometry:
  add_pixels_above: 35
  add_pixels_below: 35
  add_pixels_left: 4
  add_pixels_right: 4
data_list:
  prefix: /home/xanthos/Software/SATELLITE/data
  suffix: fit
  # Pre-suffix for error images, example: Ar3_7136e.fit
  error_img_id: e
  # Pre-suffix for data images, example: Ar3_7136s.fit
  data_img_id: s
  element_list:
    - atom: H
      spectrum: 
        i:
          atomic_list: 
            - 6563
            - 4861 
    - atom: He
      spectrum: 
        i:
          atomic_list: 
          - 5876
          - 6678
        ii:
          atomic_list: 
            - 5412
    - atom: N
      spectrum: 
        i:
          atomic_list: 
            - 5199
        ii:
          atomic_list: 
            - 5755
            - 6548
            - 6583
    - atom: O
      spectrum: 
        i:
          atomic_list: 
            - 6300
        ii:
          atomic_list: 
            - 7320
            - 7330
        iii:
          atomic_list: 
            - 4959
            - 5007
    - atom: S
      spectrum: 
        ii:
          atomic_list: 
            - 6716
            - 6731
        iii:
          atomic_list: 
            - 6312
            - 9069
    - atom: Ar
      spectrum: 
        iii:
          atomic_list: 
            - 7136
    - atom: Cl
      spectrum: 
        iii:
          atomic_list: 
            - 5517
            - 5538
analysis:
  specific_slit_analysis:
    # to skip specific slit analysis set 'skip' to true
    skip: false
    slits:
      # For each slit enter: PA, width, height, xcrd, ycrd 
      # as a comma-seperated list
      # - 79, 10, 320, 153, 106
      - 79, 8, 25, 37, 148
      - 79, 8, 21, 68, 142
      - 79, 8, 42, 104, 135
      - 79, 8, 18, 140, 128
      # - 79, 8, 8, 169, 123
      # - 79, 8, 46, 202, 116
      # - 79, 8, 25, 254, 106
    log_ratios:
      - He1_5876/H1_6563
      - He1_6678/H1_6563
      - He2_4686/H1_4861
      - He2_5412/H1_4861
      - He1_5876/He2_4686
      - He1_5876/He2_5412
      - N2_6583/H1_6563
      - N2_6548+N2_6583)/H1_6563
      - (N2_6548+N2_6583)/N2_5755
      - (N2_6548+N2_6583)/(O3_4959+O3_5007)
      - N1_5199/H1_4861
      - (S2_6716+S2_6731)/H1_6563
      - S2_6716/S2_6731
      - (S2_6716+S2_6731)/(S3_6312+S3_9069)
      - (O1_6300+O1_6363)/H1_6563
      - (O1_6300+O1_6363)/O1_5577
      - (O1_6300+O1_6363)/(O3_4959+O3_5007)
      - (O1_6300+O1_6363)/(O2_7320+O2_7330)
      - (O1_6300+O1_6363)/(O2_3727+O2_3729)
      - O1_6300_H1_6563
      - O3_5007_H1_4861
      - (O3_4959+O3_5007)/H1_4861
      - (O3_4959+O3_5007)/O3_4363
      - (O2_3727+O2_3729)/H1_4861
      - (O2_3727+O2_3729)/(O3_4959+O3_5007)
      - (O2_7320+O2_7330)/(O3_4959+O3_5007)
      - Ar4_4712_Ar4_4740
      - (Ar4_4712+Ar4_4740)/H1_4861
      - (Ne3_3868+Ne3_3967)/H1_4861
      - Cl3_5517_Cl3_5538
      - (Cl3_5517+Cl3_5538)/H1_4861
      - C1_8727_H1_6563
      - C2_6461_H1_6563
